# Azure DevOps Pipeline for Instagram OAuth Backend
# Place this in: .azure-pipelines/azure-deploy.yml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '18.x'
  appName: 'instagram-oauth-server'  # Update with your app name
  resourceGroup: 'your-resource-group'  # Update with your resource group

steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '$(nodeVersion)'
    displayName: 'Install Node.js'

  # Install dependencies
  - script: |
      npm install
    displayName: 'npm install'

  # Build (if you have a build step)
  - script: |
      npm run build || echo "No build script"
    displayName: 'Build'
    continueOnError: true

  # Deploy to Azure App Service
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Your Azure Subscription'  # Update with your service connection name
      appName: '$(appName)'
      package: '.'
      runtimeStack: 'NODE|18-lts'
      startUpCommand: 'npm start'
    displayName: 'Deploy to Azure App Service'

  # Optional: Run tests
  - script: |
      npm test || echo "No tests configured"
    displayName: 'Run Tests'
    continueOnError: true

